# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171022_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_theme',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
