# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_article_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_theme',
            field=models.CharField(max_length=200),
        ),
    ]
