# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20171030_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_theme',
            new_name='article_topic',
        ),
    ]
